In [5]:
import os
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
dataset_path = '/content/drive/MyDrive/datasets'
print(os.listdir(dataset_path))

['data.yaml', 'test', 'valid', 'train']

In [7]:
!pip install ultralytics

Requirement already satisfied: ultralytics in /usr/local/lib/python3.12/dist-packages (8.4.56)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.13.0.92)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.26.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.35.2)
Requirement already satisfied: ultralytics-thop>=2.0.18 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.19)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->ultralytics) (1.35.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2026.5.20)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.8.0->ultralytics) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)

In [8]:
from ultralytics import YOLO
from pathlib import Path
from collections import defaultdict
import random
import shutil
import yaml

In [9]:
SRC_ROOT = Path('/content/drive/MyDrive/datasets') # 修改为正确的 Google Drive 路径
DST_ROOT = Path('/content/drive/MyDrive/datasets_subset') # 处理后的子集存放路径
TRAIN_RATIO = 0.2
VAL_RATIO = 0.3
seed = 42

NAMES = ['book', 'bottole', 'earphone', 'glass', 'headphone',
         'keyboard', 'laptop', 'mobile', 'mouse', 'pen', 'penstand']
NC = len(NAMES)

In [10]:
def sample_split(split:str,ratio:float,seed:int):
    """
    随机抽样图片，复制图片和标签到新目录
    Args:
        split: 数据集划分，'train'、'val'或'test'
        ratio: 抽样比例，0-1之间
        seed: 随机种子，确保可重复抽样
    """
    random.seed(seed)
    src_img_dir=SRC_ROOT/split/'images'     # 原始图像目录
    src_label_dir=SRC_ROOT/split/'labels'

    dst_img_dir=DST_ROOT/split/'images'     # 目标图像目录
    dst_label_dir=DST_ROOT/split/'labels'

    dst_img_dir.mkdir(parents=True, exist_ok=True)      # 创建目标图像目录
    dst_label_dir.mkdir(parents=True, exist_ok=True)

    images=list(src_img_dir.glob('*.*'))     # 获取所有图像文件
    if not images:
        print(f'{split} 目录下没有找到图像文件')
        return 0,0
    k=max(1,int(len(images)*ratio))     # 计算抽样数量，至少抽取1张
    sampled=random.sample(images,k)     # 随机抽样图像文件

    copied=0
    for img_path in sampled:
        lbl_path=src_label_dir /f'{img_path.stem}.txt'     # 对应的标签文件路径
        shutil.copy2(img_path,dst_img_dir/img_path.name)     # 复制图像文件
        if lbl_path.exists():
            shutil.copy2(lbl_path,dst_label_dir/lbl_path.name)     # 复制标签文件
        copied+=1

    print(f'[{split}]抽样{copied}/{len(images)}')
    return copied,len(images)

In [11]:
def build_subset_dataset():
    """
    构建小数据集目录，并生成 data.yaml。
    """
    data_yaml = {
        "path": str(DST_ROOT.absolute()),
        "train": "train/images",
        "val": "valid/images",
        "nc": NC,
        "names": NAMES,
    }

    DST_ROOT.mkdir(parents=True, exist_ok=True)
    with open(DST_ROOT / "data.yaml", "w", encoding="utf-8") as f:
        yaml.dump(data_yaml, f, allow_unicode=True, sort_keys=False)

    print(f"已生成小数据集：{DST_ROOT}")

这一部分是用于分数据集并训练

In [ ]:
    if DST_ROOT.exists():
        print(f"删除旧数据集：{DST_ROOT}")
        shutil.rmtree(DST_ROOT)  # 递归删除整个文件夹
    sample_split("train", TRAIN_RATIO, seed)
    sample_split("valid", VAL_RATIO, seed)
    build_subset_dataset()
    model = YOLO("yolo26n.pt")
    model.train(
        data=str(DST_ROOT / "data.yaml"),
        epochs=50,
        imgsz=640,       # 输入图像大小
        verbose=False,       # 训练过程不输出详细日志
    )

这一部分是不同学习率的测试

In [9]:
import yaml
from pathlib import Path

DST_ROOT = Path('/content/drive/MyDrive/datasets_subset')

data_yaml = {
    "path": str(DST_ROOT),           # 数据集根目录
    "train": "train/images",         # 训练图片（相对于 path）
    "val": "valid/images",           # 验证图片（相对于 path）
    "nc": 11,
    "names": ['book', 'bottole', 'earphone', 'glass', 'headphone',
              'keyboard', 'laptop', 'mobile', 'mouse', 'pen', 'penstand']
}

# 写入文件
yaml_path = DST_ROOT / "data.yaml"
with open(yaml_path, 'w', encoding='utf-8') as f:
    yaml.dump(data_yaml, f, allow_unicode=True, default_flow_style=False)

print("✅ data.yaml 已配置")
print(f"\n配置内容:")
print("-" * 40)
print(yaml.dump(data_yaml, allow_unicode=True, default_flow_style=False))

# 验证路径
train_full = DST_ROOT / 'train' / 'images'
valid_full = DST_ROOT / 'valid' / 'images'

print(f"\n路径验证:")
print(f"训练图片路径: {train_full}")
print(f"  存在: {train_full.exists()}")
if train_full.exists():
    train_count = len(list(train_full.glob('*.*')))
    print(f"  图片数量: {train_count}")

print(f"\n验证图片路径: {valid_full}")
print(f"  存在: {valid_full.exists()}")
if valid_full.exists():
    valid_count = len(list(valid_full.glob('*.*')))
    print(f"  图片数量: {valid_count}")

✅ data.yaml 已配置

配置内容:
----------------------------------------
names:
- book
- bottole
- earphone
- glass
- headphone
- keyboard
- laptop
- mobile
- mouse
- pen
- penstand
nc: 11
path: /content/drive/MyDrive/datasets_subset
train: train/images
val: valid/images


路径验证:
训练图片路径: /content/drive/MyDrive/datasets_subset/train/images
  存在: True
  图片数量: 228

验证图片路径: /content/drive/MyDrive/datasets_subset/valid/images
  存在: True
  图片数量: 44

In [10]:
import pandas as pd

learning_rates=[0.001,0.005,0.01,0.02,0.05]
results_log = []
for lr in learning_rates:
  print(f"\n正在开始实验：初始学习率 lr0 = {lr}")

  # 加载模型
  model = YOLO("yolo26n.pt")

  # 训练模型
  model.train(
      data=str(DST_ROOT / "data.yaml"),
      epochs=20,
      imgsz=640,       # 输入图像大小
      batch=16,        # 批量大小
      optimizer="AdamW", # 优化器选择AdamW
      lr0=lr,          # 初始学习率
      verbose=False,   # 训练过程不输出详细日志
      name=f"exp_lr_{lr}",
      exist_ok=True    # 如果文件夹已存在，允许覆盖
    )

  # 验证模型
  val_results = model.val(verbose=False)

  # 记录结果
  results_log.append({
      '实验': f'lr={lr}',
      'optimizer': "AdamW",
      'lr0': lr,
      'epochs': 20,
      'imgsz': 640,
      'batch': 16,
      'mAP50': val_results.box.map50,
      'mAP50-95': val_results.box.map,
      'P': val_results.box.p[0] if len(val_results.box.p) > 0 else 0,
      'R': val_results.box.r[0] if len(val_results.box.r) > 0 else 0,
    })

  print(f"实验结果 (lr={lr}): mAP50={val_results.box.map50:.3f}, mAP50-95={val_results.box.map:.3f}")

# 数据整理与保存
df = pd.DataFrame(results_log)
df.to_csv('exp_result_lr.csv', index=False)

print("\n" + "="*30)
print("所有实验已完成！结果已保存至 exp_result_lr.csv")
print(df[['实验', 'mAP50', 'mAP50-95']])

正在开始实验：初始学习率 lr0 = 0.001
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 341.6MB/s 0.0s
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=exp_lr_0.001, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/exp_lr_0.001, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 146.2MB/s 0.0s
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 4.3±8.5 ms, read: 0.1±0.0 MB/s, size: 42.8 KB)
train: Scanning /content/drive/MyDrive/datasets_subset/train/labels.cache... 228 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 228/228 53.1Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 1.1±0.7 ms, read: 0.1±0.0 MB/s, size: 41.0 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 1.7Mit/s 0.0s
optimizer: AdamW(lr=0.001, momentum=0.937) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /content/runs/detect/exp_lr_0.001/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/exp_lr_0.001
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      2.49G      1.079      5.473     0.0159          4        640: 100% ━━━━━━━━━━━━ 15/15 1.9s/it 29.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 8.8s/it 17.5s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      2.87G      1.122      4.515    0.01631          4        640: 100% ━━━━━━━━━━━━ 15/15 3.4it/s 4.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.8it/s 0.3s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      2.88G       1.06      4.043    0.01663          4        640: 100% ━━━━━━━━━━━━ 15/15 3.5it/s 4.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.1it/s 1.8s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      2.88G      1.035      3.726    0.01525          4        640: 100% ━━━━━━━━━━━━ 15/15 3.2it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.4it/s 0.4s
                   all         44         67    0.00469       0.03    0.00181   0.000962

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      2.88G      1.025      3.441    0.01581          4        640: 100% ━━━━━━━━━━━━ 15/15 3.6it/s 4.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.8it/s 0.3s
                   all         44         67     0.0303       0.16      0.038     0.0265

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20      2.88G      1.074      3.247    0.01746          4        640: 100% ━━━━━━━━━━━━ 15/15 2.5it/s 5.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.5s
                   all         44         67     0.0349      0.526      0.148      0.101

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      2.88G      1.106      3.211    0.01544          4        640: 100% ━━━━━━━━━━━━ 15/15 3.8it/s 4.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.8it/s 0.3s
                   all         44         67     0.0355      0.702      0.204      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20      2.88G      1.089      2.897    0.01598          4        640: 100% ━━━━━━━━━━━━ 15/15 3.3it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.7s
                   all         44         67     0.0215      0.801      0.253      0.182

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      2.88G      1.041      2.796    0.01462          4        640: 100% ━━━━━━━━━━━━ 15/15 3.0it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.8it/s 0.3s
                   all         44         67      0.313      0.387      0.298      0.231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20      2.88G      1.023      2.689    0.01617          4        640: 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s
                   all         44         67      0.481      0.242      0.307       0.25
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20      2.88G      1.101        2.9    0.02241          4        640: 100% ━━━━━━━━━━━━ 15/15 1.9it/s 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s
                   all         44         67      0.423      0.266      0.389      0.303

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20      2.88G      1.014      2.704    0.02118          4        640: 100% ━━━━━━━━━━━━ 15/15 3.9it/s 3.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s
                   all         44         67      0.707      0.313      0.432      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20      2.88G     0.9962      2.617    0.02086          4        640: 100% ━━━━━━━━━━━━ 15/15 2.7it/s 5.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.9it/s 0.5s
                   all         44         67      0.649      0.372      0.378      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20      2.88G     0.9728      2.504    0.02037          4        640: 100% ━━━━━━━━━━━━ 15/15 4.0it/s 3.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.3it/s 0.5s
                   all         44         67      0.547      0.401      0.422      0.331

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20      2.88G     0.9612      2.425    0.01953          4        640: 100% ━━━━━━━━━━━━ 15/15 3.9it/s 3.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s
                   all         44         67      0.496      0.356      0.483      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20      2.88G     0.9047      2.313    0.01781          4        640: 100% ━━━━━━━━━━━━ 15/15 2.6it/s 5.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.1it/s 0.4s
                   all         44         67      0.502      0.402      0.488      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20      2.88G     0.8744      2.224    0.01723          4        640: 100% ━━━━━━━━━━━━ 15/15 4.0it/s 3.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s
                   all         44         67      0.728      0.374      0.479      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20      2.88G     0.8581       2.14    0.01616          4        640: 100% ━━━━━━━━━━━━ 15/15 3.5it/s 4.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s
                   all         44         67      0.737        0.4      0.478      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20      2.88G     0.8561      2.131    0.01696          4        640: 100% ━━━━━━━━━━━━ 15/15 2.9it/s 5.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s
                   all         44         67      0.723      0.402      0.492       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20      2.88G     0.8868      2.084    0.01816          4        640: 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.2it/s 0.4s
                   all         44         67      0.601      0.476      0.496      0.413

20 epochs completed in 0.044 hours.
Optimizer stripped from /content/runs/detect/exp_lr_0.001/weights/last.pt, 5.4MB
Optimizer stripped from /content/runs/detect/exp_lr_0.001/weights/best.pt, 5.4MB

Validating /content/runs/detect/exp_lr_0.001/weights/best.pt...
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s
                   all         44         67      0.601      0.476      0.496      0.413
Speed: 0.4ms preprocess, 3.9ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/exp_lr_0.001
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
val: Fast image access ✅ (ping: 0.6±0.3 ms, read: 18.3±8.8 MB/s, size: 31.9 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 10.9Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.6it/s 1.9s
                   all         44         67        0.6      0.477      0.496      0.413
Speed: 7.9ms preprocess, 13.8ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/runs/detect/val
实验结果 (lr=0.001): mAP50=0.496, mAP50-95=0.413

正在开始实验：初始学习率 lr0 = 0.005
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=exp_lr_0.005, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/exp_lr_0.005, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]

下载文件

In [20]:
!zip -r /content/runs.zip /content/runs

updating: content/runs/ (stored 0%)
updating: content/runs/detect/ (stored 0%)
updating: content/runs/detect/exp_lr_0.05/ (stored 0%)
updating: content/runs/detect/exp_lr_0.05/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.05/train_batch1.jpg (deflated 5%)
updating: content/runs/detect/exp_lr_0.05/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.05/labels.jpg (deflated 21%)
updating: content/runs/detect/exp_lr_0.05/val_batch1_pred.jpg (deflated 12%)
updating: content/runs/detect/exp_lr_0.05/confusion_matrix.png (deflated 25%)
updating: content/runs/detect/exp_lr_0.05/BoxF1_curve.png (deflated 21%)
updating: content/runs/detect/exp_lr_0.05/train_batch151.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.05/results.csv (deflated 62%)
updating: content/runs/detect/exp_lr_0.05/results.png (deflated 7%)
updating: content/runs/detect/exp_lr_0.05/args.yaml (deflated 52%)
updating: content/runs/detect/exp_lr_0.05/BoxP_curve.png (deflated 14%)
updating: content/runs/detect/exp_lr_0.05/val_batch1_labels.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.05/BoxR_curve.png (deflated 18%)
updating: content/runs/detect/exp_lr_0.05/train_batch152.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.05/BoxPR_curve.png (deflated 19%)
updating: content/runs/detect/exp_lr_0.05/train_batch2.jpg (deflated 4%)
updating: content/runs/detect/exp_lr_0.05/weights/ (stored 0%)
updating: content/runs/detect/exp_lr_0.05/weights/best.pt (deflated 12%)
updating: content/runs/detect/exp_lr_0.05/weights/last.pt (deflated 12%)
updating: content/runs/detect/exp_lr_0.05/train_batch0.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.05/confusion_matrix_normalized.png (deflated 24%)
updating: content/runs/detect/exp_lr_0.05/train_batch150.jpg (deflated 7%)
updating: content/runs/detect/val-3/ (stored 0%)
updating: content/runs/detect/val-3/val_batch0_pred.jpg (deflated 15%)
updating: content/runs/detect/val-3/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/val-3/val_batch1_pred.jpg (deflated 16%)
updating: content/runs/detect/val-3/confusion_matrix.png (deflated 24%)
updating: content/runs/detect/val-3/BoxF1_curve.png (deflated 12%)
updating: content/runs/detect/val-3/BoxP_curve.png (deflated 7%)
updating: content/runs/detect/val-3/val_batch1_labels.jpg (deflated 16%)
updating: content/runs/detect/val-3/BoxR_curve.png (deflated 13%)
updating: content/runs/detect/val-3/val_batch2_pred.jpg (deflated 12%)
updating: content/runs/detect/val-3/val_batch2_labels.jpg (deflated 11%)
updating: content/runs/detect/val-3/BoxPR_curve.png (deflated 15%)
updating: content/runs/detect/val-3/confusion_matrix_normalized.png (deflated 21%)
updating: content/runs/detect/val/ (stored 0%)
updating: content/runs/detect/val/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/val/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/val/val_batch1_pred.jpg (deflated 17%)
updating: content/runs/detect/val/confusion_matrix.png (deflated 24%)
updating: content/runs/detect/val/BoxF1_curve.png (deflated 6%)
updating: content/runs/detect/val/BoxP_curve.png (deflated 6%)
updating: content/runs/detect/val/val_batch1_labels.jpg (deflated 16%)
updating: content/runs/detect/val/BoxR_curve.png (deflated 9%)
updating: content/runs/detect/val/val_batch2_pred.jpg (deflated 11%)
updating: content/runs/detect/val/val_batch2_labels.jpg (deflated 11%)
updating: content/runs/detect/val/BoxPR_curve.png (deflated 15%)
updating: content/runs/detect/val/confusion_matrix_normalized.png (deflated 20%)
updating: content/runs/detect/val-5/ (stored 0%)
updating: content/runs/detect/val-5/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/val-5/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/val-5/val_batch1_pred.jpg (deflated 17%)
updating: content/runs/detect/val-5/confusion_matrix.png (deflated 25%)
updating: content/runs/detect/val-5/BoxF1_curve.png (deflated 21%)
updating: content/runs/detect/val-5/BoxP_curve.png (deflated 14%)
updating: content/runs/detect/val-5/val_batch1_labels.jpg (deflated 16%)
updating: content/runs/detect/val-5/BoxR_curve.png (deflated 18%)
updating: content/runs/detect/val-5/val_batch2_pred.jpg (deflated 12%)
updating: content/runs/detect/val-5/val_batch2_labels.jpg (deflated 11%)
updating: content/runs/detect/val-5/BoxPR_curve.png (deflated 19%)
updating: content/runs/detect/val-5/confusion_matrix_normalized.png (deflated 24%)
updating: content/runs/detect/exp_lr_0.001/ (stored 0%)
updating: content/runs/detect/exp_lr_0.001/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.001/train_batch1.jpg (deflated 5%)
updating: content/runs/detect/exp_lr_0.001/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.001/labels.jpg (deflated 21%)
updating: content/runs/detect/exp_lr_0.001/val_batch1_pred.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.001/confusion_matrix.png (deflated 23%)
updating: content/runs/detect/exp_lr_0.001/BoxF1_curve.png (deflated 6%)
updating: content/runs/detect/exp_lr_0.001/train_batch151.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.001/results.csv (deflated 57%)
updating: content/runs/detect/exp_lr_0.001/results.png (deflated 7%)
updating: content/runs/detect/exp_lr_0.001/args.yaml (deflated 52%)
updating: content/runs/detect/exp_lr_0.001/BoxP_curve.png (deflated 6%)
updating: content/runs/detect/exp_lr_0.001/val_batch1_labels.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.001/BoxR_curve.png (deflated 9%)
updating: content/runs/detect/exp_lr_0.001/train_batch152.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.001/BoxPR_curve.png (deflated 15%)
updating: content/runs/detect/exp_lr_0.001/train_batch2.jpg (deflated 4%)
updating: content/runs/detect/exp_lr_0.001/weights/ (stored 0%)
updating: content/runs/detect/exp_lr_0.001/weights/best.pt (deflated 11%)
updating: content/runs/detect/exp_lr_0.001/weights/last.pt (deflated 11%)
updating: content/runs/detect/exp_lr_0.001/train_batch0.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.001/confusion_matrix_normalized.png (deflated 20%)
updating: content/runs/detect/exp_lr_0.001/train_batch150.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.005/ (stored 0%)
updating: content/runs/detect/exp_lr_0.005/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.005/train_batch1.jpg (deflated 5%)
updating: content/runs/detect/exp_lr_0.005/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.005/labels.jpg (deflated 21%)
updating: content/runs/detect/exp_lr_0.005/val_batch1_pred.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.005/confusion_matrix.png (deflated 23%)
updating: content/runs/detect/exp_lr_0.005/BoxF1_curve.png (deflated 7%)
updating: content/runs/detect/exp_lr_0.005/train_batch151.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.005/results.csv (deflated 57%)
updating: content/runs/detect/exp_lr_0.005/results.png (deflated 6%)
updating: content/runs/detect/exp_lr_0.005/args.yaml (deflated 52%)
updating: content/runs/detect/exp_lr_0.005/BoxP_curve.png (deflated 6%)
updating: content/runs/detect/exp_lr_0.005/val_batch1_labels.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.005/BoxR_curve.png (deflated 10%)
updating: content/runs/detect/exp_lr_0.005/train_batch152.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.005/BoxPR_curve.png (deflated 13%)
updating: content/runs/detect/exp_lr_0.005/train_batch2.jpg (deflated 4%)
updating: content/runs/detect/exp_lr_0.005/weights/ (stored 0%)
updating: content/runs/detect/exp_lr_0.005/weights/best.pt (deflated 11%)
updating: content/runs/detect/exp_lr_0.005/weights/last.pt (deflated 11%)
updating: content/runs/detect/exp_lr_0.005/train_batch0.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.005/confusion_matrix_normalized.png (deflated 18%)
updating: content/runs/detect/exp_lr_0.005/train_batch150.jpg (deflated 7%)
updating: content/runs/detect/val-2/ (stored 0%)
updating: content/runs/detect/val-2/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/val-2/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/val-2/val_batch1_pred.jpg (deflated 16%)
updating: content/runs/detect/val-2/confusion_matrix.png (deflated 23%)
updating: content/runs/detect/val-2/BoxF1_curve.png (deflated 7%)
updating: content/runs/detect/val-2/BoxP_curve.png (deflated 6%)
updating: content/runs/detect/val-2/val_batch1_labels.jpg (deflated 16%)
updating: content/runs/detect/val-2/BoxR_curve.png (deflated 10%)
updating: content/runs/detect/val-2/val_batch2_pred.jpg (deflated 11%)
updating: content/runs/detect/val-2/val_batch2_labels.jpg (deflated 11%)
updating: content/runs/detect/val-2/BoxPR_curve.png (deflated 13%)
updating: content/runs/detect/val-2/confusion_matrix_normalized.png (deflated 18%)
updating: content/runs/detect/exp_lr_0.02/ (stored 0%)
updating: content/runs/detect/exp_lr_0.02/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.02/train_batch1.jpg (deflated 5%)
updating: content/runs/detect/exp_lr_0.02/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.02/labels.jpg (deflated 21%)
updating: content/runs/detect/exp_lr_0.02/val_batch1_pred.jpg (deflated 12%)
updating: content/runs/detect/exp_lr_0.02/confusion_matrix.png (deflated 25%)
updating: content/runs/detect/exp_lr_0.02/BoxF1_curve.png (deflated 15%)
updating: content/runs/detect/exp_lr_0.02/train_batch151.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.02/results.csv (deflated 58%)
updating: content/runs/detect/exp_lr_0.02/results.png (deflated 7%)
updating: content/runs/detect/exp_lr_0.02/args.yaml (deflated 52%)
updating: content/runs/detect/exp_lr_0.02/BoxP_curve.png (deflated 10%)
updating: content/runs/detect/exp_lr_0.02/val_batch1_labels.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.02/BoxR_curve.png (deflated 15%)
updating: content/runs/detect/exp_lr_0.02/train_batch152.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.02/BoxPR_curve.png (deflated 16%)
updating: content/runs/detect/exp_lr_0.02/train_batch2.jpg (deflated 4%)
updating: content/runs/detect/exp_lr_0.02/weights/ (stored 0%)
updating: content/runs/detect/exp_lr_0.02/weights/best.pt (deflated 12%)
updating: content/runs/detect/exp_lr_0.02/weights/last.pt (deflated 12%)
updating: content/runs/detect/exp_lr_0.02/train_batch0.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.02/confusion_matrix_normalized.png (deflated 22%)
updating: content/runs/detect/exp_lr_0.02/train_batch150.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.01/ (stored 0%)
updating: content/runs/detect/exp_lr_0.01/val_batch0_pred.jpg (deflated 15%)
updating: content/runs/detect/exp_lr_0.01/train_batch1.jpg (deflated 5%)
updating: content/runs/detect/exp_lr_0.01/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/exp_lr_0.01/labels.jpg (deflated 21%)
updating: content/runs/detect/exp_lr_0.01/val_batch1_pred.jpg (deflated 12%)
updating: content/runs/detect/exp_lr_0.01/confusion_matrix.png (deflated 24%)
updating: content/runs/detect/exp_lr_0.01/BoxF1_curve.png (deflated 12%)
updating: content/runs/detect/exp_lr_0.01/train_batch151.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.01/results.csv (deflated 57%)
updating: content/runs/detect/exp_lr_0.01/results.png (deflated 6%)
updating: content/runs/detect/exp_lr_0.01/args.yaml (deflated 52%)
updating: content/runs/detect/exp_lr_0.01/BoxP_curve.png (deflated 7%)
updating: content/runs/detect/exp_lr_0.01/val_batch1_labels.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.01/BoxR_curve.png (deflated 13%)
updating: content/runs/detect/exp_lr_0.01/train_batch152.jpg (deflated 11%)
updating: content/runs/detect/exp_lr_0.01/BoxPR_curve.png (deflated 15%)
updating: content/runs/detect/exp_lr_0.01/train_batch2.jpg (deflated 4%)
updating: content/runs/detect/exp_lr_0.01/weights/ (stored 0%)
updating: content/runs/detect/exp_lr_0.01/weights/best.pt (deflated 11%)
updating: content/runs/detect/exp_lr_0.01/weights/last.pt (deflated 11%)
updating: content/runs/detect/exp_lr_0.01/train_batch0.jpg (deflated 7%)
updating: content/runs/detect/exp_lr_0.01/confusion_matrix_normalized.png (deflated 21%)
updating: content/runs/detect/exp_lr_0.01/train_batch150.jpg (deflated 7%)
updating: content/runs/detect/val-4/ (stored 0%)
updating: content/runs/detect/val-4/val_batch0_pred.jpg (deflated 14%)
updating: content/runs/detect/val-4/val_batch0_labels.jpg (deflated 14%)
updating: content/runs/detect/val-4/val_batch1_pred.jpg (deflated 16%)
updating: content/runs/detect/val-4/confusion_matrix.png (deflated 25%)
updating: content/runs/detect/val-4/BoxF1_curve.png (deflated 15%)
updating: content/runs/detect/val-4/BoxP_curve.png (deflated 10%)
updating: content/runs/detect/val-4/val_batch1_labels.jpg (deflated 16%)
updating: content/runs/detect/val-4/BoxR_curve.png (deflated 15%)
updating: content/runs/detect/val-4/val_batch2_pred.jpg (deflated 12%)
updating: content/runs/detect/val-4/val_batch2_labels.jpg (deflated 11%)
updating: content/runs/detect/val-4/BoxPR_curve.png (deflated 16%)
updating: content/runs/detect/val-4/confusion_matrix_normalized.png (deflated 22%)
  adding: content/runs/detect/val-17/ (stored 0%)
  adding: content/runs/detect/val-17/val_batch0_pred.jpg (deflated 14%)
  adding: content/runs/detect/val-17/val_batch0_labels.jpg (deflated 14%)
  adding: content/runs/detect/val-17/val_batch1_pred.jpg (deflated 17%)
  adding: content/runs/detect/val-17/confusion_matrix.png (deflated 25%)
  adding: content/runs/detect/val-17/BoxF1_curve.png (deflated 11%)
  adding: content/runs/detect/val-17/BoxP_curve.png (deflated 8%)
  adding: content/runs/detect/val-17/val_batch1_labels.jpg (deflated 16%)
  adding: content/runs/detect/val-17/BoxR_curve.png (deflated 13%)
  adding: content/runs/detect/val-17/val_batch2_pred.jpg (deflated 12%)
  adding: content/runs/detect/val-17/val_batch2_labels.jpg (deflated 11%)
  adding: content/runs/detect/val-17/BoxPR_curve.png (deflated 15%)
  adding: content/runs/detect/val-17/confusion_matrix_normalized.png (deflated 21%)
  adding: content/runs/detect/epochs_100/ (stored 0%)
  adding: content/runs/detect/epochs_100/val_batch0_pred.jpg (deflated 14%)
  adding: content/runs/detect/epochs_100/train_batch1.jpg (deflated 5%)
  adding: content/runs/detect/epochs_100/val_batch0_labels.jpg (deflated 14%)
  adding: content/runs/detect/epochs_100/labels.jpg (deflated 21%)
  adding: content/runs/detect/epochs_100/val_batch1_pred.jpg (deflated 11%)
  adding: content/runs/detect/epochs_100/confusion_matrix.png (deflated 23%)
  adding: content/runs/detect/epochs_100/train_batch1351.jpg (deflated 12%)
  adding: content/runs/detect/epochs_100/BoxF1_curve.png (deflated 5%)
  adding: content/runs/detect/epochs_100/results.csv (deflated 60%)
  adding: content/runs/detect/epochs_100/results.png (deflated 6%)
  adding: content/runs/detect/epochs_100/args.yaml (deflated 53%)
  adding: content/runs/detect/epochs_100/BoxP_curve.png (deflated 6%)
  adding: content/runs/detect/epochs_100/val_batch1_labels.jpg (deflated 11%)
  adding: content/runs/detect/epochs_100/BoxR_curve.png (deflated 8%)
  adding: content/runs/detect/epochs_100/train_batch1350.jpg (deflated 11%)
  adding: content/runs/detect/epochs_100/BoxPR_curve.png (deflated 15%)
  adding: content/runs/detect/epochs_100/train_batch2.jpg (deflated 4%)
  adding: content/runs/detect/epochs_100/train_batch1352.jpg (deflated 14%)
  adding: content/runs/detect/epochs_100/weights/ (stored 0%)
  adding: content/runs/detect/epochs_100/weights/best.pt (deflated 11%)
  adding: content/runs/detect/epochs_100/weights/last.pt (deflated 11%)
  adding: content/runs/detect/epochs_100/train_batch0.jpg (deflated 7%)
  adding: content/runs/detect/epochs_100/confusion_matrix_normalized.png (deflated 18%)
  adding: content/runs/detect/val-14/ (stored 0%)
  adding: content/runs/detect/val-14/val_batch0_pred.jpg (deflated 15%)
  adding: content/runs/detect/val-14/val_batch0_labels.jpg (deflated 14%)
  adding: content/runs/detect/val-14/val_batch1_pred.jpg (deflated 16%)
  adding: content/runs/detect/val-14/confusion_matrix.png (deflated 24%)
  adding: content/runs/detect/val-14/BoxF1_curve.png (deflated 12%)
  adding: content/runs/detect/val-14/BoxP_curve.png (deflated 7%)
  adding: content/runs/detect/val-14/val_batch1_labels.jpg (deflated 16%)
  adding: content/runs/detect/val-14/BoxR_curve.png (deflated 13%)
  adding: content/runs/detect/val-14/val_batch2_pred.jpg (deflated 12%)
  adding: content/runs/detect/val-14/val_batch2_labels.jpg (deflated 11%)
  adding: content/runs/detect/val-14/BoxPR_curve.png (deflated 15%)
  adding: content/runs/detect/val-14/confusion_matrix_normalized.png (deflated 21%)
  adding: content/runs/detect/epochs_20/ (stored 0%)
  adding: content/runs/detect/epochs_20/val_batch0_pred.jpg (deflated 15%)
  adding: content/runs/detect/epochs_20/train_batch1.jpg (deflated 5%)
  adding: content/runs/detect/epochs_20/val_batch0_labels.jpg (deflated 14%)
  adding: content/runs/detect/epochs_20/labels.jpg (deflated 21%)
  adding: content/runs/detect/epochs_20/val_batch1_pred.jpg (deflated 12%)
  adding: content/runs/detect/epochs_20/confusion_matrix.png (deflated 24%)
  adding: content/runs/detect/epochs_20/BoxF1_curve.png (deflated 12%)
  adding: content/runs/detect/epochs_20/train_batch151.jpg (deflated 7%)
  adding: content/runs/detect/epochs_20/results.csv (deflated 57%)
  adding: content/runs/detect/epochs_20/results.png (deflated 6%)
  adding: content/runs/detect/epochs_20/args.yaml (deflated 52%)
  adding: content/runs/detect/epochs_20/BoxP_curve.png (deflated 7%)
  adding: content/runs/detect/epochs_20/val_batch1_labels.jpg (deflated 11%)
  adding: content/runs/detect/epochs_20/BoxR_curve.png (deflated 13%)
  adding: content/runs/detect/epochs_20/train_batch152.jpg (deflated 11%)
  adding: content/runs/detect/epochs_20/BoxPR_curve.png (deflated 15%)
  adding: content/runs/detect/epochs_20/train_batch2.jpg (deflated 4%)
  adding: content/runs/detect/epochs_20/weights/ (stored 0%)
  adding: content/runs/detect/epochs_20/weights/best.pt (deflated 11%)
  adding: content/runs/detect/epochs_20/weights/last.pt (deflated 11%)
  adding: content/runs/detect/epochs_20/train_batch0.jpg (deflated 7%)
  adding: content/runs/detect/epochs_20/confusion_matrix_normalized.png (deflated 21%)
  adding: content/runs/detect/epochs_20/train_batch150.jpg (deflated 7%)
  adding: content/runs/detect/batch_64/ (stored 0%)
  adding: content/runs/detect/batch_64/labels.jpg (deflated 21%)
  adding: content/runs/detect/batch_64/args.yaml (deflated 52%)
  adding: content/runs/detect/batch_64/weights/ (stored 0%)
  adding: content/runs/detect/val-24/ (stored 0%)
  adding: content/runs/detect/val-24/val_batch0_pred.jpg (deflated 15%)
  adding: content/runs/detect/val-24/val_batch0_labels.jpg (deflated 14%)
  adding: content/runs/detect/val-24/val_batch1_pred.jpg (deflated 16%)
  adding: content/runs/detect/val-24/confusion_matrix.png (deflated 24%)
  adding: content/runs/detect/val-24/BoxF1_curve.png (deflated 12%)
  adding: content/runs/detect/val-24/BoxP_curve.png (deflated 7%)
  adding: content/runs/detect/val-24/val_batch1_labels.jpg (deflated 16%)
  adding: content/runs/detect/val-24/BoxR_curve.png (deflated 13%)
  adding: content/runs/detect/val-24/val_batch2_pred.jpg (deflated 12%)
  adding: content/runs/detect/val-24/val_batch2_labels.jpg (deflated 11%)
  adding: content/runs/detect/val-24/BoxPR_curve.png (deflated 15%)
  adding: content/runs/detect/val-24/confusion_matrix_normalized.png (deflated 21%)
  adding: content/runs/detect/batch_16/ (stored 0%)
  adding: content/runs/detect/batch_16/val_batch0_pred.jpg (deflated 15%)
  adding: content/runs/detect/batch_16/train_batch1.jpg (deflated 5%)

分别进行其他实验

In [12]:
# 实验配置
EXPERIMENTS = {
    'lr': {'param': 'lr0', 'values': [0.001, 0.005, 0.01, 0.02, 0.05],
           'fixed': {'optimizer': 'AdamW', 'epochs': 20, 'imgsz': 640, 'batch': 16}},
    'batch': {'param': 'batch', 'values': [4, 8, 16],
              'fixed': {'optimizer': 'AdamW', 'lr0': 0.01, 'epochs': 20, 'imgsz': 640}},
    'weight_decay': {'param': 'weight_decay', 'values': [0.0001, 0.0005, 0.001, 0.005],
                     'fixed': {'optimizer': 'AdamW', 'lr0': 0.01, 'epochs': 20, 'imgsz': 640, 'batch': 16}},
    'optimizer': {'param': 'optimizer', 'values': ['AdamW', 'SGD', 'Adam', 'RMSprop'],
                  'fixed': {'lr0': 0.01, 'epochs': 20, 'imgsz': 640, 'batch': 16}},
    'epochs': {'param': 'epochs', 'values': [10, 20, 50, 100],
               'fixed': {'optimizer': 'AdamW', 'lr0': 0.01, 'imgsz': 640, 'batch': 16}}
}

In [15]:
import pandas as pd

def run_experiment(exp_name):
    exp = EXPERIMENTS[exp_name]
    results = []

    for value in exp['values']:
        print(f"\n训练: {exp['param']}={value}")
        model = YOLO("yolo26n.pt")

        train_params = {'data': str(DST_ROOT / "data.yaml"), 'verbose': False,
                       'name': f"{exp_name}_{value}", 'exist_ok': True, **exp['fixed']}
        train_params[exp['param']] = value

        model.train(**train_params)
        val = model.val(verbose=False)

        results.append({'参数': value, 'mAP50': val.box.map50, 'mAP50-95': val.box.map})
        print(f"mAP50={val.box.map50:.3f}")

    df = pd.DataFrame(results)
    df.to_csv(f'{exp_name}_结果.csv', index=False)
    print(f"\n保存到 {exp_name}_结果.csv")
    return df

In [ ]:
# 运行学习率实验
df = run_experiment('lr')
df

In [16]:
# 运行批量大小实验
df = run_experiment('batch')
df

训练: batch=4
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=batch_4, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/batch_4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.7±0.3 ms, read: 17.3±6.8 MB/s, size: 44.3 KB)
train: Scanning /content/drive/MyDrive/datasets_subset/train/labels.cache... 228 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 228/228 59.8Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 2.2±1.4 ms, read: 12.8±6.1 MB/s, size: 46.2 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 2.3Mit/s 0.0s
optimizer: AdamW(lr=0.01, momentum=0.937) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /content/runs/detect/batch_4/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/batch_4
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20     0.936G      1.581       5.21    0.02844          4        640: 100% ━━━━━━━━━━━━ 57/57 4.8it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.3it/s 0.5s
                   all         44         67   0.000357       0.06   0.000845   0.000229

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20     0.936G      1.888      4.674    0.03332          4        640: 100% ━━━━━━━━━━━━ 57/57 5.1it/s 11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.8it/s 0.6s
                   all         44         67      0.402     0.0125   0.000733   0.000329

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20     0.936G      2.043      4.655    0.03545          4        640: 100% ━━━━━━━━━━━━ 57/57 5.1it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all         44         67      0.502     0.0125   0.000723   0.000157

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20     0.936G      2.048      4.406    0.03907          4        640: 100% ━━━━━━━━━━━━ 57/57 6.1it/s 9.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 6.8it/s 0.9s
                   all         44         67        0.3     0.0375   0.000113   3.34e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20     0.936G      2.077      4.407     0.0381          4        640: 100% ━━━━━━━━━━━━ 57/57 5.2it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.9it/s 0.5s
                   all         44         67      0.309     0.0375    0.00456    0.00163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20     0.936G      2.093      4.381    0.03979          4        640: 100% ━━━━━━━━━━━━ 57/57 5.2it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.9it/s 0.5s
                   all         44         67      0.122     0.0843     0.0266    0.00827

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20     0.936G      1.896      4.224    0.03344          4        640: 100% ━━━━━━━━━━━━ 57/57 5.1it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.4it/s 0.5s
                   all         44         67       0.52     0.0375     0.0218    0.00507

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20     0.936G      1.984      4.138    0.03492          4        640: 100% ━━━━━━━━━━━━ 57/57 5.0it/s 11.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.0it/s 0.5s
                   all         44         67      0.838     0.0625     0.0261     0.0108

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20     0.936G      1.953       4.09    0.03381          4        640: 100% ━━━━━━━━━━━━ 57/57 5.0it/s 11.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 7.7it/s 0.8s
                   all         44         67      0.322      0.101     0.0417     0.0179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20     0.936G      1.839      4.014    0.03216          4        640: 100% ━━━━━━━━━━━━ 57/57 5.9it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 7.8it/s 0.8s
                   all         44         67      0.452     0.0918     0.0593     0.0222
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20     0.936G      1.979      4.347    0.04945          4        640: 100% ━━━━━━━━━━━━ 57/57 5.4it/s 10.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.3it/s 0.6s
                   all         44         67      0.643       0.07      0.104     0.0342

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20     0.936G      1.824      4.075    0.04458          4        640: 100% ━━━━━━━━━━━━ 57/57 5.2it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.0it/s 0.5s
                   all         44         67      0.726      0.115      0.107     0.0392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20     0.936G      1.799      4.022    0.04253          4        640: 100% ━━━━━━━━━━━━ 57/57 5.2it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.8it/s 0.6s
                   all         44         67      0.804      0.109      0.106     0.0476

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20     0.936G      1.864       3.89    0.04472          4        640: 100% ━━━━━━━━━━━━ 57/57 5.3it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.9it/s 0.6s
                   all         44         67      0.744      0.103      0.126     0.0729

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20     0.936G       1.79      3.863    0.04307          4        640: 100% ━━━━━━━━━━━━ 57/57 5.7it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 7.7it/s 0.8s
                   all         44         67       0.37      0.142      0.133     0.0547

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20     0.936G       1.74      3.803    0.04142          4        640: 100% ━━━━━━━━━━━━ 57/57 5.9it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.2it/s 0.5s
                   all         44         67      0.394      0.125      0.116     0.0577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20     0.936G      1.766      3.899    0.03955          4        640: 100% ━━━━━━━━━━━━ 57/57 5.2it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.4it/s 0.5s
                   all         44         67      0.553      0.143      0.154     0.0634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20     0.936G       1.77      3.683    0.04067          4        640: 100% ━━━━━━━━━━━━ 57/57 5.3it/s 10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 11.0it/s 0.5s
                   all         44         67      0.746      0.105      0.157     0.0726

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20     0.936G      1.735       3.72    0.04116          4        640: 100% ━━━━━━━━━━━━ 57/57 5.4it/s 10.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 7.2it/s 0.8s
                   all         44         67      0.755      0.105      0.178     0.0804

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20     0.936G      1.738      3.655    0.04112          4        640: 100% ━━━━━━━━━━━━ 57/57 6.2it/s 9.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 7.2it/s 0.8s
                   all         44         67      0.757      0.102      0.183     0.0868

20 epochs completed in 0.067 hours.
Optimizer stripped from /content/runs/detect/batch_4/weights/last.pt, 5.4MB
Optimizer stripped from /content/runs/detect/batch_4/weights/best.pt, 5.4MB

Validating /content/runs/detect/batch_4/weights/best.pt...
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.7it/s 2.2s
                   all         44         67      0.757      0.102      0.183     0.0871
Speed: 1.3ms preprocess, 24.5ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /content/runs/detect/batch_4
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
val: Fast image access ✅ (ping: 0.7±0.2 ms, read: 18.9±8.1 MB/s, size: 32.9 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 13.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.6it/s 1.9s
                   all         44         67      0.757      0.102      0.186     0.0883
Speed: 7.9ms preprocess, 6.7ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /content/runs/detect/val-12
mAP50=0.186

训练: batch=8
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=batch_8, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/batch_8, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

   参数     mAP50  mAP50-95
0   4  0.186286  0.088288
1   8  0.155888  0.092885
2  16  0.188231  0.120971

In [17]:
# 运行权重衰减实验
df = run_experiment('weight_decay')
df

训练: weight_decay=0.0001
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=weight_decay_0.0001, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/weight_decay_0.0001, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.8±0.3 ms, read: 21.4±5.6 MB/s, size: 44.3 KB)
train: Scanning /content/drive/MyDrive/datasets_subset/train/labels.cache... 228 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 228/228 41.6Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.6±0.5 ms, read: 5.7±3.6 MB/s, size: 46.2 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 2.9Mit/s 0.0s
optimizer: AdamW(lr=0.01, momentum=0.937) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0001), 126 bias(decay=0.0)
Plotting labels to /content/runs/detect/weight_decay_0.0001/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/weight_decay_0.0001
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      2.63G      1.256       5.59    0.01953          4        640: 100% ━━━━━━━━━━━━ 15/15 2.0it/s 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.1it/s 0.4s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      2.79G      1.598      4.581    0.02632          4        640: 100% ━━━━━━━━━━━━ 15/15 1.8it/s 8.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.6it/s 0.4s
                   all         44         67   0.000885      0.025     0.0123    0.00465

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      2.79G       1.64      4.067    0.02923          4        640: 100% ━━━━━━━━━━━━ 15/15 3.2it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.5it/s 0.3s
                   all         44         67   0.000573      0.154   0.000438   9.24e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      2.79G      1.769      4.025    0.03123          4        640: 100% ━━━━━━━━━━━━ 15/15 2.5it/s 5.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.9it/s 0.7s
                   all         44         67   3.63e-05     0.0111   5.17e-06   5.17e-07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      2.79G       1.71      3.746    0.02973          4        640: 100% ━━━━━━━━━━━━ 15/15 3.3it/s 4.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.2it/s 0.4s
                   all         44         67    5.7e-05     0.0347    1.3e-05   3.42e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20      2.79G      1.846      3.802    0.03391          4        640: 100% ━━━━━━━━━━━━ 15/15 3.4it/s 4.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s
                   all         44         67    0.00216      0.153    0.00174    0.00041

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      2.79G      1.788      3.807     0.0278          4        640: 100% ━━━━━━━━━━━━ 15/15 2.6it/s 5.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s
                   all         44         67      0.506     0.0343    0.00318   0.000538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20      2.79G      1.825      3.634    0.03069          4        640: 100% ━━━━━━━━━━━━ 15/15 3.4it/s 4.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s
                   all         44         67    0.00367      0.255    0.00343    0.00125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      2.79G       1.71      3.579    0.02797          4        640: 100% ━━━━━━━━━━━━ 15/15 2.3it/s 6.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.3it/s 0.4s
                   all         44         67      0.604      0.145    0.00995    0.00162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20      2.79G      1.681      3.429    0.03015          4        640: 100% ━━━━━━━━━━━━ 15/15 3.5it/s 4.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.9it/s 0.3s
                   all         44         67      0.117       0.13     0.0107    0.00329
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20      2.79G      1.717      3.722    0.03868          4        640: 100% ━━━━━━━━━━━━ 15/15 1.7it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         44         67       0.34     0.0726     0.0661     0.0332

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20      2.79G      1.609        3.5    0.03547          4        640: 100% ━━━━━━━━━━━━ 15/15 3.6it/s 4.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.9it/s 0.4s
                   all         44         67      0.409     0.0675     0.0611     0.0275

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20      2.79G      1.635      3.472    0.03642          4        640: 100% ━━━━━━━━━━━━ 15/15 3.2it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s
                   all         44         67      0.354     0.0793     0.0447     0.0174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20      2.79G      1.607      3.106    0.03729          4        640: 100% ━━━━━━━━━━━━ 15/15 3.0it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s
                   all         44         67      0.382      0.133      0.103     0.0548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20      2.79G      1.604      3.173    0.03597          4        640: 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.6it/s 0.4s
                   all         44         67      0.373      0.199      0.154     0.0633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20      2.79G      1.664      3.015    0.03836          4        640: 100% ━━━━━━━━━━━━ 15/15 2.4it/s 6.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.5it/s 0.4s
                   all         44         67      0.296      0.198      0.171      0.104

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20      2.79G       1.57      2.944    0.03359          4        640: 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.7it/s 0.4s
                   all         44         67      0.357      0.209      0.175      0.101

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20      2.79G      1.513      2.899    0.03248          4        640: 100% ━━━━━━━━━━━━ 15/15 3.4it/s 4.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s
                   all         44         67      0.691      0.173      0.226      0.135

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20      2.79G      1.546      2.732    0.03548          4        640: 100% ━━━━━━━━━━━━ 15/15 2.9it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s
                   all         44         67      0.552      0.289      0.295       0.18

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20      2.79G      1.522      2.659    0.03568          4        640: 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s
                   all         44         67      0.545       0.35      0.322      0.204

20 epochs completed in 0.037 hours.
Optimizer stripped from /content/runs/detect/weight_decay_0.0001/weights/last.pt, 5.4MB
Optimizer stripped from /content/runs/detect/weight_decay_0.0001/weights/best.pt, 5.4MB

Validating /content/runs/detect/weight_decay_0.0001/weights/best.pt...
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s
                   all         44         67      0.545       0.35       0.32      0.203
Speed: 0.3ms preprocess, 3.0ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/runs/detect/weight_decay_0.0001
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
val: Fast image access ✅ (ping: 0.7±0.2 ms, read: 20.4±9.3 MB/s, size: 32.9 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 13.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.6it/s 1.9s
                   all         44         67      0.546       0.35      0.319      0.204
Speed: 15.8ms preprocess, 6.0ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/runs/detect/val-15
mAP50=0.319

训练: weight_decay=0.0005
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=weight_decay_0.0005, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/weight_decay_0.0005, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights

       参数     mAP50  mAP50-95
0  0.0001  0.319230  0.203661
1  0.0005  0.188231  0.120971
2  0.0010  0.264940  0.149327
3  0.0050  0.249233  0.132273

In [18]:
# 运行优化器实验
df = run_experiment('optimizer')
df

训练: optimizer=AdamW
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=optimizer_AdamW, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/optimizer_AdamW, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.7±0.3 ms, read: 24.2±7.4 MB/s, size: 44.3 KB)
train: Scanning /content/drive/MyDrive/datasets_subset/train/labels.cache... 228 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 228/228 41.6Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.6±0.4 ms, read: 20.6±15.9 MB/s, size: 46.2 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 2.5Mit/s 0.0s
optimizer: AdamW(lr=0.01, momentum=0.937) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /content/runs/detect/optimizer_AdamW/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/optimizer_AdamW
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20       2.6G      1.299      5.512    0.02078          4        640: 100% ━━━━━━━━━━━━ 15/15 1.7it/s 8.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.0it/s 0.3s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      2.76G      1.594      4.448    0.02596          4        640: 100% ━━━━━━━━━━━━ 15/15 3.3it/s 4.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.2it/s 0.4s
                   all         44         67     0.0029        0.1    0.00674    0.00236

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      2.76G      1.678      4.119    0.02956          4        640: 100% ━━━━━━━━━━━━ 15/15 2.5it/s 6.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s
                   all         44         67    0.00121      0.205    0.00494    0.00182

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      2.76G      1.671      4.073    0.02841          4        640: 100% ━━━━━━━━━━━━ 15/15 3.4it/s 4.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s
                   all         44         67      0.517       0.01    0.00246   0.000271

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      2.76G      1.691      3.919    0.02929          4        640: 100% ━━━━━━━━━━━━ 15/15 2.2it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s
                   all         44         67    0.00175     0.0386   0.000368   0.000123

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20      2.76G      1.832      3.935    0.03285          4        640: 100% ━━━━━━━━━━━━ 15/15 3.4it/s 4.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.3it/s 0.4s
                   all         44         67      0.101     0.0786   0.000426   0.000103

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      2.76G      1.853      4.026    0.02981          4        640: 100% ━━━━━━━━━━━━ 15/15 3.1it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.7s
                   all         44         67      0.107     0.0958    0.00396   0.000679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20      2.76G      1.798      3.813     0.0304          4        640: 100% ━━━━━━━━━━━━ 15/15 2.8it/s 5.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s
                   all         44         67       0.52     0.0375     0.0141    0.00487

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      2.76G      1.691      3.728    0.02715          4        640: 100% ━━━━━━━━━━━━ 15/15 3.5it/s 4.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.0it/s 0.5s
                   all         44         67      0.422     0.0643     0.0166    0.00429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20      2.76G      1.768      3.639    0.03125          4        640: 100% ━━━━━━━━━━━━ 15/15 2.3it/s 6.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s
                   all         44         67      0.229     0.0929     0.0168    0.00629
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20      2.76G      1.741      3.922    0.03804          4        640: 100% ━━━━━━━━━━━━ 15/15 2.3it/s 6.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s
                   all         44         67      0.545     0.0736     0.0539     0.0214

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20      2.76G      1.603      3.744    0.03502          4        640: 100% ━━━━━━━━━━━━ 15/15 2.4it/s 6.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s
                   all         44         67      0.356      0.138     0.0813     0.0336

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20      2.76G      1.664      3.762    0.03887          4        640: 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s
                   all         44         67      0.583     0.0693      0.097     0.0501

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20      2.76G      1.571      3.458    0.03573          4        640: 100% ━━━━━━━━━━━━ 15/15 3.0it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.0it/s 0.5s
                   all         44         67      0.513      0.219      0.232      0.105

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20      2.76G      1.595      3.511    0.03506          4        640: 100% ━━━━━━━━━━━━ 15/15 2.9it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s
                   all         44         67      0.389      0.292      0.241      0.108

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20      2.76G      1.542      3.425    0.03561          4        640: 100% ━━━━━━━━━━━━ 15/15 3.5it/s 4.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s
                   all         44         67      0.394      0.198      0.188      0.121

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20      2.76G       1.58      3.289    0.03258          4        640: 100% ━━━━━━━━━━━━ 15/15 2.4it/s 6.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s
                   all         44         67      0.446      0.189       0.17     0.0999

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20      2.76G      1.529      3.228    0.03193          4        640: 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.5it/s 0.4s
                   all         44         67      0.366      0.177      0.174      0.103

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20      2.76G      1.506      3.127    0.03422          4        640: 100% ━━━━━━━━━━━━ 15/15 2.7it/s 5.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         44         67      0.221      0.182        0.2      0.109

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20      2.76G      1.503      3.057    0.03361          4        640: 100% ━━━━━━━━━━━━ 15/15 3.2it/s 4.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.7it/s 0.3s
                   all         44         67      0.289      0.177      0.224      0.117

20 epochs completed in 0.037 hours.
Optimizer stripped from /content/runs/detect/optimizer_AdamW/weights/last.pt, 5.4MB
Optimizer stripped from /content/runs/detect/optimizer_AdamW/weights/best.pt, 5.4MB

Validating /content/runs/detect/optimizer_AdamW/weights/best.pt...
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.9it/s 0.5s
                   all         44         67      0.394      0.196      0.188      0.121
Speed: 0.3ms preprocess, 2.8ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/runs/detect/optimizer_AdamW
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
val: Fast image access ✅ (ping: 0.3±0.1 ms, read: 14.0±6.1 MB/s, size: 32.9 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 9.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.6s
                   all         44         67      0.394      0.197      0.188      0.121
Speed: 10.8ms preprocess, 11.3ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to /content/runs/detect/val-19
mAP50=0.188

训练: optimizer=SGD
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=optimizer_SGD, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/optimizer_SGD, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

        参数     mAP50  mAP50-95
0    AdamW  0.188231  0.120971
1      SGD  0.597570  0.486187
2     Adam  0.257595  0.161418
3  RMSprop  0.556735  0.439639

In [19]:
# 运行训练轮数实验
df = run_experiment('epochs')
df

训练: epochs=10
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=epochs_10, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/epochs_10, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.3±0.1 ms, read: 25.7±16.4 MB/s, size: 44.3 KB)
train: Scanning /content/drive/MyDrive/datasets_subset/train/labels.cache... 228 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 228/228 47.8Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 1.3±0.9 ms, read: 10.7±7.1 MB/s, size: 46.2 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 1.8Mit/s 0.0s
optimizer: AdamW(lr=0.01, momentum=0.937) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /content/runs/detect/epochs_10/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/epochs_10
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      2.56G      1.324      7.792    0.02895          4        640: 100% ━━━━━━━━━━━━ 15/15 2.0it/s 7.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.8it/s 0.3s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10      2.72G      1.652       4.94    0.03768          4        640: 100% ━━━━━━━━━━━━ 15/15 2.6it/s 5.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.5it/s 0.3s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10      2.72G      1.951      4.427    0.04696          4        640: 100% ━━━━━━━━━━━━ 15/15 3.5it/s 4.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.3it/s 0.4s
                   all         44         67   0.000444      0.114    0.00104   0.000265

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10      2.72G      1.988      4.249    0.04561          4        640: 100% ━━━━━━━━━━━━ 15/15 2.4it/s 6.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.7it/s 0.4s
                   all         44         67      0.208      0.153    0.00604    0.00168

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10      2.72G      1.935      4.151    0.04439          4        640: 100% ━━━━━━━━━━━━ 15/15 3.5it/s 4.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.2it/s 0.3s
                   all         44         67      0.323     0.0979    0.00625    0.00105

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10      2.72G      1.869      4.037    0.04127          4        640: 100% ━━━━━━━━━━━━ 15/15 2.8it/s 5.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s
                   all         44         67      0.414      0.107     0.0195     0.0046

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10      2.72G      1.784      3.845    0.04082          4        640: 100% ━━━━━━━━━━━━ 15/15 3.1it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.8it/s 0.3s
                   all         44         67      0.464     0.0804     0.0475     0.0169

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10      2.72G      1.696      3.639    0.03929          4        640: 100% ━━━━━━━━━━━━ 15/15 3.6it/s 4.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.7it/s 0.4s
                   all         44         67      0.382      0.108      0.193     0.0656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10      2.72G       1.74      3.591    0.04025          4        640: 100% ━━━━━━━━━━━━ 15/15 2.4it/s 6.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.6it/s 0.4s
                   all         44         67      0.258       0.26      0.196     0.0819

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10      2.72G      1.771      3.602    0.03845          4        640: 100% ━━━━━━━━━━━━ 15/15 3.6it/s 4.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8it/s 0.4s
                   all         44         67      0.478      0.236      0.223      0.108

10 epochs completed in 0.018 hours.
Optimizer stripped from /content/runs/detect/epochs_10/weights/last.pt, 5.4MB
Optimizer stripped from /content/runs/detect/epochs_10/weights/best.pt, 5.4MB

Validating /content/runs/detect/epochs_10/weights/best.pt...
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s
                   all         44         67      0.288      0.263      0.224      0.108
Speed: 0.3ms preprocess, 3.4ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/runs/detect/epochs_10
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,981 parameters, 0 gradients, 5.2 GFLOPs
val: Fast image access ✅ (ping: 0.6±0.3 ms, read: 20.0±9.5 MB/s, size: 32.9 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 11.5Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.7it/s 1.8s
                   all         44         67      0.478      0.236      0.223      0.108
Speed: 11.1ms preprocess, 5.6ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /content/runs/detect/val-23
mAP50=0.223

训练: epochs=20
Ultralytics 8.4.56 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/datasets_subset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=epochs_20, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/epochs_20, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245466  ultralytics.nn.modules.head.Detect           [11, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,508,090 parameters, 2,508,090 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.7±0.3 ms, read: 24.0±6.5 MB/s, size: 44.3 KB)
train: Scanning /content/drive/MyDrive/datasets_subset/train/labels.cache... 228 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 228/228 56.3Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.7±0.8 ms, read: 14.7±6.4 MB/s, size: 46.2 KB)
val: Scanning /content/drive/MyDrive/datasets_subset/valid/labels.cache... 44 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 44/44 3.1Mit/s 0.0s
optimizer: AdamW(lr=0.01, momentum=0.937) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /content/runs/detect/epochs_20/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/epochs_20
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      2.63G      1.299      5.512    0.02078          4        640: 100% ━━━━━━━━━━━━ 15/15 1.9it/s 8.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 6.3it/s 0.3s
                   all         44         67          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20       2.8G      1.594      4.448    0.02596          4        640: 100% ━━━━━━━━━━━━ 15/15 3.3it/s 4.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.1it/s 0.4s
                   all         44         67     0.0029        0.1    0.00674    0.00236

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20       2.8G      1.678      4.119    0.02956          4        640: 100% ━━━━━━━━━━━━ 15/15 2.2it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s
                   all         44         67    0.00121      0.205    0.00494    0.00182

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20       2.8G      1.671      4.073    0.02841          4        640: 100% ━━━━━━━━━━━━ 15/15 3.3it/s 4.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s
                   all         44         67      0.517       0.01    0.00246   0.000271

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20       2.8G      1.691      3.919    0.02929          4        640: 100% ━━━━━━━━━━━━ 15/15 2.2it/s 6.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.5it/s 0.4s
                   all         44         67    0.00175     0.0386   0.000368   0.000123

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20       2.8G      1.832      3.935    0.03285          4        640: 100% ━━━━━━━━━━━━ 15/15 3.4it/s 4.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.0it/s 0.4s
                   all         44         67      0.101     0.0786   0.000426   0.000103

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20       2.8G      1.853      4.026    0.02981          4        640: 100% ━━━━━━━━━━━━ 15/15 3.0it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.5s
                   all         44         67      0.107     0.0958    0.00396   0.000679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20       2.8G      1.798      3.813     0.0304          4        640: 100% ━━━━━━━━━━━━ 15/15 2.9it/s 5.3s

    参数     mAP50  mAP50-95
0   10  0.223314  0.108280
1   20  0.188231  0.120971
2   50  0.487880  0.299541
3  100  0.543527  0.406020